### ISSUE TITLE
Clean up creating mocks

### ISSUE THREAD

**Issue by neu5** [neu5-przenz-games/the-game#442]
Use dynamic imports
- [ ] #448 clean up generating config
- [ ] #449 clean up generating objects
- [ ] #450 clean up generating mobs
